include(${CMAKE_CURRENT_LIST_DIR}/CNPM_ADD_PACKAGE.cmake)

include(
    ${CMAKE_CURRENT_LIST_DIR}/NPM_GENERATE_PACKAGE_NAME.cmake
)

include(
    ${CMAKE_CURRENT_LIST_DIR}/NPM_PREPARE_PACKAGE.cmake
)

include(${CMAKE_CURRENT_LIST_DIR}/CNPM_PREPARE_PACKAGES.cmake)

include(
    ${CMAKE_CURRENT_LIST_DIR}/CNPM_INSTALL_EXPLICIT.cmake
)
